config/routes.rb
Rails.application.routes.draw do
  resources :posts do
    resource :map
  end
  
  resources :tags
  
  root to: 'posts#index'

end

app/models/post.rb
class Post < ActiveRecord::Base
  has_attached_file :picture,
    styles: { medium: "300x300>" },
    :storage => :s3,
    :s3_credentials => {
      :bucket => 'instagramjune',
      :access_key_id => Rails.application.secrets.s3_access_key_id,
      :secret_access_key => Rails.application.secrets.s3_secret_access_key
    }

  validates_attachment_content_type :picture, :content_type => /\Aimage\/.*\Z/
  has_and_belongs_to_many :tags

  def tag_list
  end

  def tag_list=(some_tags)
    return if some_tags.empty?

    some_tags.split(', ').uniq.each do |tag|
      self.tags << Tag.find_or_create_by(text: tag)
    end
  end

end

app/models/tag.rb
class Tag < ActiveRecord::Base
  has_and_belongs_to_many :posts

  def to_param
    text.delete('#')
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/maps_controller.rb
class MapsController < ApplicationController
  def show
    @post = Post.find(params[:post_id])
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  def index
    @posts = Post.all
  end

  def new
    @post = Post.new
  end

  def create
    @post = Post.new(params[:post].permit(:title, :picture, :tag_list, :address))
    @post.save
    redirect_to '/posts'
  end

  def show
    @post = Post.find(params[:id])
  end
end

app/controllers/tags_controller.rb
class TagsController < ApplicationController
  def show
    @tag = Tag.find_by!(text: '#' + params[:id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/maps_helper.rb
module MapsHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/tags_helper.rb
module TagsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <%= csrf_meta_tags %>
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track' => true %>
    <title>Instagramjune</title>
  </head>

  <body>

    <div class="navbar navbar-inverse navbar-fixed-top" role="navigation">
      <div class="container">
        <div class="navbar-header">
          <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
          <a class="navbar-brand" href="#">Instagramjune</a>
        </div>
        <div class="navbar-collapse collapse">
          <form class="navbar-form navbar-right" role="form">
            <div class="form-group">
              <input type="text" placeholder="Email" class="form-control">
            </div>
            <div class="form-group">
              <input type="password" placeholder="Password" class="form-control">
            </div>
            <button type="submit" class="btn btn-success">Sign in</button>
          </form>
        </div><!--/.navbar-collapse -->
      </div>
    </div>


    <main class='container'>
      <%= yield %>
    </main>
    <script src='http://maps.google.com/maps/api/js?sensor=true'></script>
    <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>

  </body>
</html>

app/views/maps/show.html.erb
<div id='map' data-id='<%= @post.id %>'>
</div>

app/views/posts/_post.html.erb
<article class='post col-sm-6 col-md-4'>

  <div class="panel panel-default">
    <div class="panel-heading">
      <h3><%= post.title %></h3>
    </div>
    <div class="panel-body">
      <% if post.picture.present? %>
        <%= image_tag post.picture.url(:medium), class: 'uploaded-pic' %>
      <% end %>

      <section class='tags hidden-xs'>
        <% post.tags.each do |tag| %>
          <%= link_to tag.text, tag %>
        <% end %>
        
        <% unless post.address.blank? %>
          <%= link_to 'Map', post_map_path(post), class: 'btn btn-danger' %>
        <% end %>
      </section>
    </div>
  </div>  

</article>

app/views/posts/index.html.erb
<% if @posts.any? %>

  <% @posts.in_groups_of(3, false) do |post_triplet| %>
    <section class='row'>
      <%= render post_triplet %>
    </section>
  <% end %>
  
<% else %> 
  No posts yet
<% end %>

<%= link_to new_post_path, class: 'btn btn-lg btn-success' do %>
  <span class='hidden-xs'>New post</span>
  <span class="glyphicon glyphicon-pencil"></span>
<% end %>

app/views/posts/new.html.erb
<%= form_for @post, html: { multipart: true } do |f| %>
  <%= f.label :title %>
  <%= f.text_field :title %>

  <%= f.label :tag_list, 'Tags' %>
  <%= f.text_field :tag_list %>

  <%= f.label :address %>
  <%= f.text_field :address %>

  <%= f.label :picture %>
  <%= f.file_field :picture %>
  
  <%= f.submit 'Create post' %>
<% end %>

app/views/tags/show.html.erb
<h1>Posts tagged with <%= @tag.text %></h1>

<%= render @tag.posts %>